In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline 
import sklearn

In [2]:
data = pd.read_csv('data/charts.csv')
data.head(5)

,title,rank,date,artist,url,region,chart,trend,streams
0,Chantaje (feat. Maluma),1,2017-01-01,Shakira,https://open.spotify.com/track/6mICuAdrwEjh6Y6...,Argentina,top200,SAME_POSITION,253019.0
1,Vente Pa' Ca (feat. Maluma),2,2017-01-01,Ricky Martin,https://open.spotify.com/track/7DM4BPaS7uofFul...,Argentina,top200,MOVE_UP,223988.0
2,Reggaet贸n Lento (Bailemos),3,2017-01-01,CNCO,https://open.spotify.com/track/3AEZUABDXNtecAO...,Argentina,top200,MOVE_DOWN,210943.0
3,Safari,4,2017-01-01,"J Balvin, Pharrell Williams, BIA, Sky",https://open.spotify.com/track/6rQSrBHf7HlZjtc...,Argentina,top200,SAME_POSITION,173865.0
4,Shaky Shaky,5,2017-01-01,Daddy Yankee,https://open.spotify.com/track/58IL315gMSTD37D...,Argentina,top200,MOVE_UP,153956.0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26173514 entries, 0 to 26173513
Data columns (total 9 columns):
 #   Column   Dtype
---  ------   -----
 0   title    object
 1   rank     int64
 2   date     object
 3   artist   object
 4   url      object
 5   region   object
 6   chart    object
 7   trend    object
 8   streams  float64
dtypes: float64(1), int64(1), object(7)
memory usage: 1.8+ GB

In [4]:
data.drop(["url"],inplace=True,axis=1)

In [5]:
df = data

df['date'] = pd.to_datetime(df['date'])
df.head(5)

,title,rank,date,artist,region,chart,trend,streams
0,Chantaje (feat. Maluma),1,2017-01-01,Shakira,Argentina,top200,SAME_POSITION,253019.0
1,Vente Pa' Ca (feat. Maluma),2,2017-01-01,Ricky Martin,Argentina,top200,MOVE_UP,223988.0
2,Reggaet贸n Lento (Bailemos),3,2017-01-01,CNCO,Argentina,top200,MOVE_DOWN,210943.0
3,Safari,4,2017-01-01,"J Balvin, Pharrell Williams, BIA, Sky",Argentina,top200,SAME_POSITION,173865.0
4,Shaky Shaky,5,2017-01-01,Daddy Yankee,Argentina,top200,MOVE_UP,153956.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26173514 entries, 0 to 26173513
Data columns (total 8 columns):
 #   Column   Dtype
---  ------   -----
 0   title    object
 1   rank     int64
 2   date     datetime64[ns]
 3   artist   object
 4   region   object
 5   chart    object
 6   trend    object
 7   streams  float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 1.6+ GB

In [7]:
Title = []
Feature= []
df['title']=df['title'].astype(str)
for i in df["title"]:
    if i.find("(feat.")!=-1:
        new= i.split('(feat.')
        title= new[0]
        feature= new[1].split(')')
        Title.append(title)
        Feature.append(feature)
       
    else:
        Title.append(i)
        Feature.append("None")

In [ ]:
df["feature"]= Feature
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26173514 entries, 0 to 26173513
Data columns (total 9 columns):
 #   Column   Dtype
---  ------   -----
 0   title    object
 1   rank     int64
 2   date     datetime64[ns]
 3   artist   object
 4   region   object
 5   chart    object
 6   trend    object
 7   streams  float64
 8   feature  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(6)
memory usage: 1.8+ GB

In [ ]:
df.head(10)

,title,rank,date,artist,region,chart,trend,streams,feature
0,Chantaje (feat. Maluma),1,2017-01-01,Shakira,Argentina,top200,SAME_POSITION,253019.0,"[ Maluma, ]"
1,Vente Pa' Ca (feat. Maluma),2,2017-01-01,Ricky Martin,Argentina,top200,MOVE_UP,223988.0,"[ Maluma, ]"
2,Reggaet贸n Lento (Bailemos),3,2017-01-01,CNCO,Argentina,top200,MOVE_DOWN,210943.0,None
3,Safari,4,2017-01-01,"J Balvin, Pharrell Williams, BIA, Sky",Argentina,top200,SAME_POSITION,173865.0,None
4,Shaky Shaky,5,2017-01-01,Daddy Yankee,Argentina,top200,MOVE_UP,153956.0,None
5,Traicionera,6,2017-01-01,Sebastian Yatra,Argentina,top200,MOVE_DOWN,151140.0,None
6,Cuando Se Pone a Bailar,7,2017-01-01,Rombai,Argentina,top200,MOVE_DOWN,148369.0,None
7,Otra vez (feat. J Balvin),8,2017-01-01,Zion & Lennox,Argentina,top200,MOVE_DOWN,143004.0,"[ J Balvin, ]"
8,La Bicicleta,9,2017-01-01,"Carlos Vives, Shakira",Argentina,top200,MOVE_UP,126389.0,None
9,Dile Que Tu Me Quieres,10,2017-01-01,Ozuna,Argentina,top200,MOVE_DOWN,112012.0,None

,title,rank,date,artist,region,chart,trend,streams
0,Chantaje (feat. Maluma),1,2017-01-01,Shakira,Argentina,top200,SAME_POSITION,253019.0
1,Vente Pa' Ca (feat. Maluma),2,2017-01-01,Ricky Martin,Argentina,top200,MOVE_UP,223988.0
2,Reggaet贸n Lento (Bailemos),3,2017-01-01,CNCO,Argentina,top200,MOVE_DOWN,210943.0
3,Safari,4,2017-01-01,"J Balvin, Pharrell Williams, BIA, Sky",Argentina,top200,SAME_POSITION,173865.0
4,Shaky Shaky,5,2017-01-01,Daddy Yankee,Argentina,top200,MOVE_UP,153956.0
5,Traicionera,6,2017-01-01,Sebastian Yatra,Argentina,top200,MOVE_DOWN,151140.0
6,Cuando Se Pone a Bailar,7,2017-01-01,Rombai,Argentina,top200,MOVE_DOWN,148369.0
7,Otra vez (feat. J Balvin),8,2017-01-01,Zion & Lennox,Argentina,top200,MOVE_DOWN,143004.0
8,La Bicicleta,9,2017-01-01,"Carlos Vives, Shakira",Argentina,top200,MOVE_UP,126389.0
9,Dile Que Tu Me Quieres,10,2017-01-01,Ozuna,Argentina,top200,MOVE_DOWN,112012.0

,title,rank,date,artist,region,chart,trend,streams,Feature
0,Chantaje (feat. Maluma),1,2017-01-01,Shakira,Argentina,top200,SAME_POSITION,253019.0,"[ Maluma, ]"
1,Vente Pa' Ca (feat. Maluma),2,2017-01-01,Ricky Martin,Argentina,top200,MOVE_UP,223988.0,"[ Maluma, ]"
2,Reggaet贸n Lento (Bailemos),3,2017-01-01,CNCO,Argentina,top200,MOVE_DOWN,210943.0,None
3,Safari,4,2017-01-01,"J Balvin, Pharrell Williams, BIA, Sky",Argentina,top200,SAME_POSITION,173865.0,None
4,Shaky Shaky,5,2017-01-01,Daddy Yankee,Argentina,top200,MOVE_UP,153956.0,None
5,Traicionera,6,2017-01-01,Sebastian Yatra,Argentina,top200,MOVE_DOWN,151140.0,None
6,Cuando Se Pone a Bailar,7,2017-01-01,Rombai,Argentina,top200,MOVE_DOWN,148369.0,None
7,Otra vez (feat. J Balvin),8,2017-01-01,Zion & Lennox,Argentina,top200,MOVE_DOWN,143004.0,"[ J Balvin, ]"
8,La Bicicleta,9,2017-01-01,"Carlos Vives, Shakira",Argentina,top200,MOVE_UP,126389.0,None
9,Dile Que Tu Me Quieres,10,2017-01-01,Ozuna,Argentina,top200,MOVE_DOWN,112012.0,None